### ISSUE TITLE
Code for segmentation network training

### ISSUE THREAD

**Issue by Sierkinhane** [rulixiang/vwe#2]
Hello, will you plan to provide the source code for training a deeplabv2 model as described in your paper?

**Comment by rulixiang** [comment]
Hey, for code of the segmentation network, you could use https://github.com/kazuto1011/deeplab-pytorch or https://github.com/rulixiang/deeplab-pytorch.

**Comment by Sierkinhane** [comment]
Thanks!

**Comment by Sierkinhane** [comment]
Hello, would you like to share the pretrained weights on coco and imagenet for training deeplabv2? The link in https://github.com/rulixiang/deeplab-pytorch for accessing pretrained weights is missing.

**Comment by rulixiang** [comment]
Hey, I've updated the [README](https://github.com/rulixiang/deeplab-pytorch/blob/master/README.md#train-and-test-1). You can now download the coco pretrained weights from https://drive.google.com/file/d/1IRLbL0DwZkmqlWhQKEdKzr3P23gb-lOV/view.

**Comment by Sierkinhane** [comment]
Hey, how about the weights pretrained on ImageNet.

**Comment by Sierkinhane** [comment]
I found that you report both the results of pretrained on imagenet and ms-coco dataset. Would you like to share imagenet pretrained weights too!

**Comment by rulixiang** [comment]
I now uploaded the ImageNet pretrained weights, please see https://drive.google.com/drive/folders/188dmsGNifP5bWHxsJVi84QgWfgYm315a?usp=sharing.

**Comment by Sierkinhane** [comment]
Great! Thanks for your reply!
