### ISSUE TITLE
why the v2 code  gain only 43% miou?

### ISSUE THREAD

**Issue by ziqi-jin** [rulixiang/vwe#4]
你好，我跑了v2 版本的代码只获得了 43%的miou，我发现您注释了一些代码，请问我需要复原您注释掉的代码吗。 或者是您的参数设置与论文中有区别导致的？

Hello, I ran the v2 version of the code and only got 43% of miou. I found that you commented some code. Do I need to restore the code you commented out. Or is it caused by the difference between your parameter settings and the paper?

**Comment by rulixiang** [comment]
你好，[这里的参数](https://github.com/rulixiang/vwe/blob/adcd6ebaec47af06befc6e36117d358b2b8e89f0/v2/network/resnet_cam.py#L9)论文中应该是2，
可能我做对比实验后没注意就上传代码了，非常抱歉，请你修改后再试试。

**Comment by ziqi-jin** [comment]
好的 ，谢谢您了
